### ISSUE TITLE
Support mobile emulation

### ISSUE THREAD

**Issue by whimboo** [w3c/webdriver-bidi#772]
Both Puppeteer and Playwright support an `isMobile` boolean argument for the `setViewport` command, which is currently missing in WebDriver BiDi. We should add support for this parameter with the following behavior:

- **Default Behavior**: By default `isMobile` is set to `false`, meaning the device is not treated as a mobile device and touch events are not enabled.
  
- **Mobile Mode**: When `isMobile` is set to `true`, the browser will behave as if it's running on a mobile device. This includes rendering the website in mobile mode by taking the `meta viewport` tag and CSS media queries into account. Additionally, touch events are enabled, allowing mobile interactions like swiping and tapping.

Question: We currently support `touch` events in `input.performActions` by default. How should these behave when mobile mode is disabled? Should we consider disallowing their use in this case?

**Comment by whimboo** [comment]
> Question: We currently support `touch` events in `input.performActions` by default. How should these behave when mobile mode is disabled? Should we consider disallowing their use in this case?

There is actually a `hasTouch` argument as well that we do not cover yet and I filed https://github.com/w3c/webdriver-bidi/issues/773 for.

**Comment by lutien** [comment]
@OrKoN, @sadym-chromium, I'm gathering requirements for this feature, and I'm trying to understand now what is actually implemented behind "mobile" argument of "Emulation.setDeviceMetricsOverride" command. [It said in the CDP documentation](https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#method-setDeviceMetricsOverride):

>  Whether to emulate mobile device. This includes viewport meta tag, overlay scrollbars, text autosizing and more.

I think `viewport meta tag` and `overlay scrollbars` is clear, but could expand on `text autosizing`? And also what hides behind `more` ? 🙂

**Comment by gsnedders** [comment]
> [@OrKoN](https://github.com/OrKoN), [@sadym-chromium](https://github.com/sadym-chromium), I'm gathering requirements for this feature, and I'm trying to understand now what is actually implemented behind "mobile" argument of "Emulation.setDeviceMetricsOverride" command. [It said in the CDP documentation](https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#method-setDeviceMetricsOverride):
> 
> > Whether to emulate mobile device. This includes viewport meta tag, overlay scrollbars, text autosizing and more.
> 
> I think `viewport meta tag` and `overlay scrollbars` is clear, but could expand on `text autosizing`? And also what hides behind `more` ? 🙂

I think anything like this depends a lot on what we're putting into this bucket — and it's not like there's clear delineations between what's mobile and what's not (e.g., Safari on iPadOS, on most iPad models, matches Safari on macOS for all these in their default configurations).

In general I'm slightly weary about bucketing this all together at a protocol layer, but it does provide some forwards-compatible way if browsers introduce new "mobile" adjustments.

"text autosizing" is what `text-size-adjust` controls: https://developer.mozilla.org/en-US/docs/Web/CSS/text-size-adjust (the spec is near non-existent).

We also need to figure out what behaviour should be if the desktop browser doesn't support all these configuration options.

**Comment by OrKoN** [comment]
So the [mobile flags sets the screenType](https://source.chromium.org/chromium/chromium/src/+/main:content/browser/devtools/protocol/emulation_handler.cc;l=748;drc=48d6f7175422b2c969c14258f9f8d5b196c28d18) to mobile in emulation params for Blink. Then in blink it [results in a creation of a screen emulator](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/frame/web_frame_widget_impl.cc;l=2303;drc=48d6f7175422b2c969c14258f9f8d5b196c28d18). Some mobile-pecific things there:

1) https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/frame/screen_metrics_emulator.cc;l=87;drc=48d6f7175422b2c969c14258f9f8d5b196c28d18
2) https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/frame/screen_metrics_emulator.cc;l=100;drc=48d6f7175422b2c969c14258f9f8d5b196c28d18
3) https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/frame/screen_metrics_emulator.cc;l=115;drc=48d6f7175422b2c969c14258f9f8d5b196c28d18

And then except for the screen emulation the following are the [blink settings](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/inspector/dev_tools_emulator.cc;l=385;drc=48d6f7175422b2c969c14258f9f8d5b196c28d18) that are changed:

1) Android overlay scrollbar 
2) Various viewport flags 
3) ShrinksViewportContentToFit
4) Text preferences
5) Zoom/scale overrides

**Comment by sadym-chromium** [comment]
Emulate enabled touch events: https://github.com/w3c/webdriver-bidi/issues/1028

**Comment by sadym-chromium** [comment]
Scrollbar emulation PR: https://github.com/w3c/webdriver-bidi/pull/1050

**Comment by sadym-chromium** [comment]
Text sizing sub-issue: https://github.com/w3c/webdriver-bidi/issues/1051

**Comment by sadym-chromium** [comment]
Media Feature sub-issue: ~~https://github.com/w3c/webdriver-bidi/issues/1052~~ https://github.com/w3c/webdriver-bidi/issues/750

**Comment by sadym-chromium** [comment]
Viewport meta sub-issue: https://github.com/w3c/webdriver-bidi/issues/1053

**Comment by sadym-chromium** [comment]
Safe areas sub-issue: https://github.com/w3c/webdriver-bidi/issues/1054

**Comment by gsnedders** [comment]
> In general I'm slightly weary about bucketing this all together at a protocol layer, but it does provide some forwards-compatible way if browsers introduce new "mobile" adjustments.

From a Safari point-of-view, I think we have roughly three common modes:

 * What Safari on macOS does (which doesn't even have most of these mobile things in the binary),
 * What Safari on iOS/iPadOS does on smaller form factor devices,
 * What Safari on iPadOS does on larger form factor devices.

I believe visionOS matches one of the iPadOS modes, and while WebKit exists as private API on other Apple platforms it really is mostly just niche uses (and okay, you can open links from Mail/Messages/etc. on watchOS, but the main web developer constraint there is really "you're looking at a really small screen").

Combinations of settings except for what those modes make possible, even if you could force them, are kinda uninteresting — because (almost?) no real user will be in them.

We could specify something taking `"desktop" / "mobile" / "tablet"`, but it's not implausible that implementations would deviate from this over time. For example, if Safari on visionOS were to start to deviate from iPadOS, would that justify adding a new alternate, or would that cause tests that currently work to stop working for reasons unrelated to the configuration? And clearly, that doesn't account for the fact that which mode is the default for iPadOS depends on the iPad model.

The bucketing almost seems like it has to be per-product, and thus hard to specify, and liable to change over time (e.g., see the introduction of "desktop-class browsing" on iPadOS), though clearly it's something that users would like to make easy.

All in all, I'm not sure what the right option is here.

**Comment by sadym-chromium** [comment]
Even though the "bucket" approach seems the easiest and fastest, there shouldn't be much overhead in **precisely specifying individual features**, and it would even allow for some exotic emulations like **foldable**, **dual-screen** or **wearable** devices.

The following list covers the nuances in how Chromium handles mobile emulation ( @OrKoN, did I miss anything?):

* [x] **[Touch events](https://github.com/w3c/webdriver-bidi/issues/1028)**: Enable touch-based interactions.
* [x] **[Scrollbar emulation](https://github.com/w3c/webdriver-bidi/pull/1064)**: Support for mobile-style overlay scrollbars.
* [x] **[Text sizing](https://github.com/w3c/webdriver-bidi/issues/1051)**: Handling text autosizing and font floors.
* [x] **[Media Features](https://github.com/w3c/webdriver-bidi/issues/750)**: Emulating mobile-specific CSS media queries.
* [x] **[Viewport Meta](https://github.com/w3c/webdriver-bidi/issues/1053)**: Forcing respect for the `viewport` meta tag.
* [ ] **[Safe area insets](https://github.com/w3c/webdriver-bidi/issues/1054)**: Emulating notches and display cutouts.
* [x] **[UA-CH](https://github.com/WICG/ua-client-hints/issues/386)**: User-Agent Client Hints (tracked in the external specification).
* [ ] **[Virtual Keyboard](https://github.com/w3c/webdriver-bidi/issues/1059)**: Show / Hide the Virtual Keyboard.
* [ ] **[Browser UI State](https://github.com/w3c/webdriver-bidi/issues/1060)**: Toggle the Browser's UI state.

To address complexity, we could introduce a list of **known device configurations** that defines the specific features required to emulate common devices.
